version: '3'
services:
  # Sole purpose to run tests
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: pytest tests -v -s
  # hobby-pack-app:
  #   restart: always
  #   build: .
  #   ports: 
  #     - "8001:8001"
  #   env_file:
  #     - ./app.env
  #   environment:
  #     - SECRET_KEY=${SECRET_KEY}
  #   volumes:
  #     - .:/app
  # To test dev
  hobby-pack-app:
    restart: always
    build: .
    ports: 
      - "8001:8001"
    env_file:
      - ./app.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app

    # depends_on:
    # - postgres

#   postgres:
#     restart: always
#     image: postgres
#     env_file:
#       - ./app.env
#     # volumes:
#     #   - ./postgres-data/postgres:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
# # SYNTAX IS ALWAYS: 
# # [HOST]:[CONTAINER]