FROM python:alpine

# EXPOSE 5433

# MAINTAINER Luis Orozco <humbledore@gmail.com>

# RUN apt-get update -y && \
#     apt-get install -y python-pip python-dev

WORKDIR '/app'

ADD . .

RUN apk add --virtual deps gcc python-dev musl-dev postgresql-dev

RUN pip install -r requirements.txt

RUN pip install python-dotenv

# RUN pip install flask
# RUN pip install sqlalchemy
# RUN pip install flask-sqlalchemy

EXPOSE 7001

CMD python main.py