# SYNTAX IS ALWAYS: 
# [HOST]:[CONTAINER]
version: '3'
services:
  # Sole purpose to run tests
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: pytest tests -v -s
  
  # DEV env
  hobby-pack:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "7001:7001"
    env_file:
      - ./app.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
    container_name: hobby_pack_dev_container
    image: hobby_pack_dev_image
    #For debugging (remove for PROD)
    stdin_open: true
    tty: true
  
  # PROD env (if there was any using docker-compose) --> This doesn't apply
  # hobby-pack-prod:
  #   restart: always
  #   build: .
  #   ports: 
  #     - "8001:8001"
  #   env_file:
  #     - ./app.env
  #   environment:
  #     - SECRET_KEY=${SECRET_KEY}
  #   volumes:
  #     - .:/app