FROM python:alpine

WORKDIR '/app'

ADD . .

RUN apk add --virtual deps gcc python-dev musl-dev postgresql-dev

RUN pip install -r requirements.txt

# For testing
RUN pip install pytest

# For debugging locally
RUN pip install pdbpp

COPY ./tests ./tests

EXPOSE 7001

# To run locally
CMD python main.py

# To run in prod
# CMD gunicorn main:app --bind 0.0.0.0:7001 --reload